### ISSUE TITLE
[FEATURE] Install bootloader to MBR

### ISSUE THREAD

**Issue by DogOSdev** [DogOSdev/DogOSinstaller#1]
## Sources
- [MBR (x86) - OSDev Wiki](https://wiki.osdev.org/MBR_(x86)#x86_Examples)

## To-do
- [ ] Format drive.
- [ ] Get to the MBR sector.
- [ ] Add bootloader to the MBR.
- [ ] Add OS files to the disk.

## Infomation
If anyone has any sources to help, please make a comment. :)
